version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d30ctg71jsu9"
s3_prefix = "sam-app-stack"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UsersTableName=\"users\""
